steps:
  
- id: "GO Version"
  name: "gcr.io/cloud-builders/go"
  args: ["version"]
  env: ["GOPATH=."]

- id: g"Go Test"
  name: "gcr.io/cloud-builders/go"
  args: ["test","calc_test"]
  env: ["GOPATH=."]

- id: " RUN "
name: "gcr.io/cloud-builders/go"
args: ["run","helloworld"]
env: ["GOPATH=."]
